services:
  - type: worker
    name: fontify-bot
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: OWNER_ID
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
    autoDeploy: false
