services:
  - type: worker
    name: fontify-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: MONGO_URI
        sync: false